# IAS 150 Data

Note: See the python file for 'migrant_functions.py' for functions and their documentation

### Imports

In [1]:
import pandas as pd
import numpy as np
import migrant_functions as mf
import qgrid as qg

### Data Cleaning

In [2]:
male_migrants = mf.load_data_excel('male_migrants.xlsx')
female_migrants = mf.load_data_excel('female_migrants.xlsx')
total_migrants = mf.load_data_excel('total_migrants.xlsx')

In [11]:
total_migrants

,Year,Country,Code,Total,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,...,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe
13,1990,Burundi,108,333110,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1990,Comoros,174,14079,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1990,Djibouti,262,122221,0,0,0,0,0,0,...,0,0,0,0,0,0,0,289,0,0
16,1990,Eritrea,232,11848,0,0,0,0,0,247,...,0,0,0,0,0,0,0,0,91,82
17,1990,Ethiopia,231,1155390,0,0,0,0,0,0,...,0,0,0,0,0,0,0,68,0,0
18,1990,Kenya,404,297292,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,1990,Madagascar,450,23917,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,1990,Malawi,454,1127724,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,5637,3851
21,1990,Mauritius,480,3613,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1990,Mayotte,175,15229,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1990,Mozambique,508,122332,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1288,8455
24,1990,Réunion,638,57210,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,1990,Rwanda,646,159869,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1990,Seychelles,690,3721,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1990,Somalia,706,478294,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,1990,South Sudan,728,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1990,Uganda,800,558307,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,1990,United Republic of Tanzania,834,574025,0,0,0,0,0,717,...,0,0,0,0,0,0,0,0,18188,488
31,1990,Zambia,894,279029,0,0,0,0,0,123777,...,0,0,0,0,0,0,0,0,0,34625
32,1990,Zimbabwe,716,626821,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,17966,0
34,1990,Angola,24,33517,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,119,0
35,1990,Cameroon,120,265344,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,1990,Central African Republic,140,67234,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,1990,Chad,148,74342,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,1990,Congo,178,129597,0,0,0,0,0,10334,...,0,0,0,0,0,0,0,0,0,0
39,1990,Democratic Republic of the Congo,180,754194,0,0,0,0,0,468462,...,0,0,0,0,0,0,0,0,0,0
40,1990,Equatorial Guinea,226,2740,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,1990,Gabon,266,127980,0,0,34,0,0,342,...,0,0,0,0,0,0,0,0,0,0
42,1990,Sao Tome and Principe,678,5582,0,0,0,0,0,468,...,0,0,0,0,0,0,0,0,0,0
44,1990,Algeria,12,273954,0,0,0,0,0,0,...,0,0,0,0,0,0,167905,2593,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1854,2017,Uruguay,858,79586,0,0,0,0,0,0,...,0,0,0,588,0,0,0,0,0,0
1855,2017,Venezuela (Bolivarian Republic of),862,1426336,0,19,96,0,0,190,...,4869,0,0,0,12,0,0,0,0,15
1857,2017,Bermuda,60,18954,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1858,2017,Canada,124,7861226,47605,15823,59389,0,0,2981,...,7672,5574,0,18608,191988,0,0,1976,3742,10532
1859,2017,Greenland,304,6014,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1860,2017,Saint Pierre and Miquelon,666,990,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1861,2017,United States of America,840,49776970,72909,90381,19316,0,0,13841,...,51229,60216,0,232448,1409063,0,0,44905,24455,54567
1864,2017,Australia,36,7035560,39297,3495,1636,398,0,608,...,11679,1703,1648,5132,238307,0,0,707,7465,40724
1865,2017,New Zealand,554,1067423,2607,0,0,0,0,0,...,0,0,0,0,6563,0,0,0,1510,8640
1867,2017,Fiji,242,13911,0,0,0,0,0,0,...,0,0,186,0,0,0,0,0,0,0
1868,2017,New Caledonia,540,66001,0,0,823,0,0,0,...,0,0,5069,0,819,8010,0,0,0,0
1869,2017,Papua New Guinea,598,32389,0,0,0,0,0,0,...,0,0,104,0,0,0,0,0,0,0
1870,2017,Solomon Islands,90,2532,0,0,0,0,0,0,...,0,0,64,0,0,0,0,0,0,0
1871,2017,Vanuatu,548,3245,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1873,2017,Guam,316,78027,0,0,0,0,0,0,...,0,0,0,0,363,0,0,0,0,0
1874,2017,Kiribati,296,3022,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1875,2017,Marshall Islands,584,3292,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1876,2017,Micronesia (Fed. States of),583,2785,0,0,0,23,0,0,...,0,0,0,0,0,0,0,0,0,0
1877,2017,Nauru,520,3710,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1878,2017,Northern Mariana Islands,580,21777,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1879,2017,Palau,585,4988,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1881,2017,American Samoa,16,23561,0,0,0,0,0,0,...,0,0,0,0,211,0,0,0,0,0
1882,2017,Cook Islands,184,4213,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1883,2017,French Polynesia,258,30687,0,0,695,0,0,0,...,0,0,214,0,0,33,0,0,0,0
1884,2017,Niue,570,553,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1885,2017,Samoa,882,4879,0,0,0,1571,0,0,...,0,0,16,0,0,0,0,0,0,0
1886,2017,Tokelau,772,504,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1887,2017,Tonga,776,4952,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1888,2017,Tuvalu,798,143,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1889,2017,Wallis and Futuna Islands,876,2779,0,0,0,0,0,0,...,0,0,240,0,0,0,0,0,0,0

In [3]:
female_migrants_revised = mf.master(female_migrants)
male_migrants_revised = mf.master(male_migrants)
total_migrants_revisedz = mf.master(total_migrants)

Cuba
El Salvador
Guatemala
Honduras
Mexico
Venezuela (Bolivarian Republic of)
China
India
Philippines
Viet Nam
Afghanistan
Iraq
Pakistan
Syrian Arab Republic
Ethiopia
Ghana
Kenya
Nigeria
Somalia
South Africa
Cuba
El Salvador
Guatemala
Honduras
Mexico
Venezuela (Bolivarian Republic of)
China
India
Philippines
Viet Nam
Afghanistan
Iraq
Pakistan
Syrian Arab Republic
Ethiopia
Ghana
Kenya
Nigeria
Somalia
South Africa
Cuba
El Salvador
Guatemala
Honduras
Mexico
Venezuela (Bolivarian Republic of)
China
India
Philippines
Viet Nam
Afghanistan
Iraq
Pakistan
Syrian Arab Republic
Ethiopia
Ghana
Kenya
Nigeria
Somalia
South Africa

In [10]:
display(female_migrants_revised.head())
display(male_migrants_revised.head())
display(total_migrants_revisedz.head())

,Code,Country,Year,Migration Type,Total Migration,Country 1,Country 1 Count,Country 2,Country 2 Count,Country 3,Country 3 Count,Country 4,Country 4 Count,Country 5,Country 5 Count
0,840,Cuba,1990,Emigration,436429,United States of America,385969,Spain,12590,Puerto Rico,10069,Venezuela (Bolivarian Republic of),5685,Dominican Republic,2924
0,Cuba,Cuba,1990,Immigration,17277,Spain,5309,Russian Federation,2763,Ukraine,907,United States of America,609,Haiti,585
0,840,Cuba,1995,Emigration,489315,United States of America,425624,Spain,16056,Puerto Rico,10027,Italy,5642,Venezuela (Bolivarian Republic of),5137
0,Cuba,Cuba,1995,Immigration,13628,Spain,4190,Russian Federation,2181,Ukraine,716,United States of America,481,Haiti,462
0,840,Cuba,2000,Emigration,549465,United States of America,465038,Spain,25468,Italy,10341,Puerto Rico,10012,Venezuela (Bolivarian Republic of),4737

,Code,Country,Year,Migration Type,Total Migration,Country 1,Country 1 Count,Country 2,Country 2 Count,Country 3,Country 3 Count,Country 4,Country 4 Count,Country 5,Country 5 Count
0,840,Cuba,1990,Emigration,835546,United States of America,736971,Spain,21854,Puerto Rico,19579,Venezuela (Bolivarian Republic of),11559,Dominican Republic,6824
0,Cuba,Cuba,1990,Immigration,34555,Spain,10703,Russian Federation,4491,Haiti,2063,Ukraine,1367,United States of America,1186
0,840,Cuba,1995,Emigration,935377,United States of America,815617,Spain,28314,Puerto Rico,19293,Venezuela (Bolivarian Republic of),10603,Dominican Republic,7580
0,Cuba,Cuba,1995,Immigration,26187,Spain,8112,Russian Federation,3404,Haiti,1564,Ukraine,1036,United States of America,899
0,840,Cuba,2000,Emigration,1049902,United States of America,894876,Spain,45738,Puerto Rico,19054,Italy,11659,Venezuela (Bolivarian Republic of),9928

,Code,Country,Year,Migration Type,Total Migration,Country 1,Country 1 Count,Country 2,Country 2 Count,Country 3,Country 3 Count,Country 4,Country 4 Count,Country 5,Country 5 Count
0,840,Cuba,1990,Emigration,835546,United States of America,736971,Spain,21854,Puerto Rico,19579,Venezuela (Bolivarian Republic of),11559,Dominican Republic,6824
0,Cuba,Cuba,1990,Immigration,34555,Spain,10703,Russian Federation,4491,Haiti,2063,Ukraine,1367,United States of America,1186
0,840,Cuba,1995,Emigration,935377,United States of America,815617,Spain,28314,Puerto Rico,19293,Venezuela (Bolivarian Republic of),10603,Dominican Republic,7580
0,Cuba,Cuba,1995,Immigration,26187,Spain,8112,Russian Federation,3404,Haiti,1564,Ukraine,1036,United States of America,899
0,840,Cuba,2000,Emigration,1049902,United States of America,894876,Spain,45738,Puerto Rico,19054,Italy,11659,Venezuela (Bolivarian Republic of),9928

In [ ]:
female_migrants_revised.to_csv('female_migrants.csv')
female_migrants_revised.to_csv('male_migrants.csv')
female_migrants_revised.to_csv('total_migrants_origin_dest.csv')

In [4]:
Central_America = ['Cuba', 'El Salvador', 'Guatemala', 'Honduras', 'Mexico', 'Venezuela (Bolivarian Republic of)']
Asia = ['China','India','Philippines','Vietnam']
Middle_East = ['Afghanistan', 'Iraq', 'Pakistan', 'Syria']
Africa = ['Ethiopia', 'Ghana', 'Kenya', 'Nigeria', 'Somalia', 'South Africa']
Central_America + Asia + Middle_East + Africa

['Cuba',
 'El Salvador',
 'Guatemala',
 'Honduras',
 'Mexico',
 'Venezuela (Bolivarian Republic of)',
 'China',
 'India',
 'Philippines',
 'Vietnam',
 'Afghanistan',
 'Iraq',
 'Pakistan',
 'Syria',
 'Ethiopia',
 'Ghana',
 'Kenya',
 'Nigeria',
 'Somalia',
 'South Africa']

In [9]:
central_origin =  mf.select_region(male_migrants, Central_America, origin=True)
central_destination = mf.select_region(male_migrants, Central_America, origin=False)

Get the top 3 countries, destination and origin, for Cuba.

This function supports:
    
    1) country selection
    2) selection of how many of the top origin/destination countries to display
    3) Whether were looking at in-migration or out-migration from the selected country
    4) The year to be looked at

In [10]:
central_destination[(central_destination['Country'] == 'Cuba')
                   & (central_destination['Year'] == 1990)]['Total'].values[0]

34555

In [11]:
central_origin_three = mf.get_top_i(central_origin,'Cuba',1990,origin=True,i=5)
central_destination_three = mf.get_top_i(central_destination,'Cuba',1990,origin=False,i=5)

In [13]:
central_origin_three[0]

,Year,Code,Country of Destination,Country of Origin: Cuba (Counts)
241,1990,1990242,United States of America,736971
172,1990,1990173,Spain,21854
204,1990,1990205,Puerto Rico,19579
235,1990,1990236,Venezuela (Bolivarian Republic of),11559
197,1990,1990198,Dominican Republic,6824

In [8]:
mf.table_to_row(central_origin_three, 'Cuba', origin=True)

,Year,Country,Code,Migration Type,Total MigrationCountry 1,Country 1 Count,Country 2,Country 2 Count,Country 3,Country 3 Count,Country 4,Country 4 Count,Country 5,Country 5 Count
0,1990,Cuba,1990242,Emigration,835546,United States of America,736971,Spain,21854,Puerto Rico,19579,Venezuela (Bolivarian Republic of),11559,Dominican Republic

In [20]:
pd.read_csv('male_migration_by_origin_destination')

,Unnamed: 0,Code,Country,Year,Migration Type,Country 1,Country 1 Count,Country 2,Country 2 Count,Country 3,Country 3 Count,Country 4,Country 4 Count,Country 5,Country 5 Count
0,0,1990242,Cuba,1990,Emigration,United States of America,736971,Spain,21854,Puerto Rico,19579,Venezuela (Bolivarian Republic of),11559,Dominican Republic,6824
1,0,1990195,Cuba,1990,Immigration,Spain,10703,Russian Federation,4491,Haiti,2063,Ukraine,1367,United States of America,1186
2,0,1995242,Cuba,1995,Emigration,United States of America,815617,Spain,28314,Puerto Rico,19293,Venezuela (Bolivarian Republic of),10603,Dominican Republic,7580
3,0,1995195,Cuba,1995,Immigration,Spain,8112,Russian Federation,3404,Haiti,1564,Ukraine,1036,United States of America,899
4,0,2000242,Cuba,2000,Emigration,United States of America,894876,Spain,45738,Puerto Rico,19054,Italy,11659,Venezuela (Bolivarian Republic of),9928
5,0,2000195,Cuba,2000,Immigration,Spain,5521,Russian Federation,2317,Haiti,1065,Ukraine,705,United States of America,612
6,0,2005242,Cuba,2005,Emigration,United States of America,959480,Spain,71614,Italy,22561,Puerto Rico,17039,Venezuela (Bolivarian Republic of),10372
7,0,2005195,Cuba,2005,Immigration,Spain,5499,Russian Federation,2308,Haiti,1061,Ukraine,702,United States of America,609
8,0,2010242,Cuba,2010,Emigration,United States of America,1055229,Spain,103189,Italy,33463,Canada,13340,Puerto Rico,12882
9,0,2010195,Cuba,2010,Immigration,Spain,5024,Russian Federation,2108,Haiti,969,Ukraine,641,United States of America,556
10,0,2015242,Cuba,2015,Emigration,United States of America,1210873,Spain,131134,Italy,33469,Mexico,17653,Canada,14918
11,0,2015195,Cuba,2015,Immigration,Spain,4522,Russian Federation,1897,Haiti,872,Ukraine,577,United States of America,500
12,0,2017242,Cuba,2017,Emigration,United States of America,1251037,Spain,132378,Italy,34057,Mexico,18111,Canada,15509
13,0,2017195,Cuba,2017,Immigration,Spain,4454,Russian Federation,1868,Haiti,858,Ukraine,568,United States of America,492
14,0,1990242,El Salvador,1990,Emigration,United States of America,465433,Mexico,301106,Guatemala,236655,Honduras,114810,Costa Rica,56257
15,0,1990216,El Salvador,1990,Immigration,Honduras,15774,Guatemala,8235,United States of America,8033,Nicaragua,3893,Mexico,2457
16,0,1995242,El Salvador,1995,Emigration,United States of America,649970,Guatemala,124346,Honduras,60692,Canada,32598,Costa Rica,26046
17,0,1995216,El Salvador,1995,Immigration,Honduras,12650,Guatemala,7224,United States of America,6306,Nicaragua,4219,Mexico,1948
18,0,2000242,El Salvador,2000,Emigration,United States of America,838090,Canada,38826,Guatemala,12037,Australia,10690,Costa Rica,8857
19,0,2000216,El Salvador,2000,Immigration,Honduras,9525,Guatemala,6212,United States of America,4603,Nicaragua,4545,Mexico,1438
20,0,2005242,El Salvador,2005,Emigration,United States of America,997858,Canada,39970,Guatemala,14364,Australia,10760,Italy,8882
21,0,2005216,El Salvador,2005,Immigration,Honduras,10362,Guatemala,7367,Nicaragua,6024,United States of America,4871,Mexico,1541
22,0,2010242,El Salvador,2010,Emigration,United States of America,1192423,Canada,43655,Guatemala,16691,Costa Rica,13688,Italy,12462
23,0,2010216,El Salvador,2010,Immigration,Honduras,11198,Guatemala,8521,Nicaragua,7502,United States of America,5176,Mexico,1644
24,0,2015242,El Salvador,2015,Emigration,United States of America,1347952,Canada,48820,Guatemala,19198,Costa Rica,13900,Italy,12464
25,0,2015216,El Salvador,2015,Immigration,Honduras,11676,Guatemala,8885,Nicaragua,7823,United States of America,5397,Mexico,1714
26,0,2017242,El Salvador,2017,Emigration,United States of America,1392663,Canada,50756,Guatemala,19976,Costa Rica,13984,Italy,12683
27,0,2017216,El Salvador,2017,Immigration,Honduras,11753,Guatemala,8943,Nicaragua,7874,United States of America,5432,Mexico,1725
28,0,1990242,Guatemala,1990,Emigration,United States of America,225739,Mexico,72343,Belize,12650,Canada,8559,El Salvador,8235
29,0,1990217,Guatemala,1990,Immigration,El Salvador,236655,United States of America,5822,Mexico,5402,Honduras,4768,Nicaragua,3726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,0,2017242,Nigeria,2017,Emigration,United States of America,282153,United Kingdom,209417,Cameroon,115519,Niger,98849,Ghana,70705
251,0,2017071,Nigeria,2017,Immigration,Benin,362544,Ghana,229048,Mali,165795,Togo,152128,Niger,116114
252,0,1990018,Somalia,1990,Emigration,Ethiopia,616940,Djibouti,101216,Yemen,36771,Canada,19517,Italy,11363
253,0,1990028,Somalia,1990,Immigration,Ethiopia,460000,Afghanistan,0,Peru,0,Nicaragua,0,Niger,0
254,0,1995018,Somalia,1995,Emigration,Ethiopia,459615,Kenya,103743,Djibouti,82625,Yemen,61684,Libya,40088
255,0,1995028,Somalia,1995,Immigration,Ethiopia,18044,Afghanistan,0,Peru,0,Nicaragua,0,Niger,0
256,0,2000018,Somalia,2000,Emigration,Ethiopia,389419,Kenya,159197,Djibouti,83230,Libya,76918,Yemen,69012
257,0,2000028,Somalia,2000,Immigration,Ethiopia,555,Afghanistan,0,Peru,0,Nicaragua,0,Niger,0
258,0,2005018,Somalia,2005,Emigration,Ethiopia,327545,Kenya,259706,Yemen,92122,Libya,84755,United States of America,76917
259,0,2005028,Somalia,2005,Immigration,Ethiopia,1142,Eritrea,17,Afghanistan,0,Paraguay,0,Nicaragua,0
260,0,2010019,Somalia,2010,Emigration,Kenya,398753,Ethiopia,361609,Yemen,194393,United States of America,120575,United Kingdom,98604
261,0,2010028,Somalia,2010,Immigration,Ethiopia,1882,Eritrea,37,Afghanistan,0,Paraguay,0,Nicaragua,0
262,0,2015019,Somalia,2015,Emigration,Kenya,488470,Ethiopia,442910,Yemen,275683,United Kingdom,114110,Libya,104539
263,0,2015028,Somalia,2015,Immigration,Ethiopia,13079,Yemen,5883,Eritrea,34,Afghanistan,0,Paraguay,0
264,0,2017019,Somalia,2017,Emigration,Kenya,485864,Ethiopia,467508,Yemen,278891,United Kingdom,119953,Libya,106880
265,0,2017028,Somalia,2017,Immigration,Ethiopia,13732,Yemen,8141,Eritrea,35,Afghanistan,0,Paraguay,0
266,0,1990157,South Africa,1990,Emigration,United Kingdom,66921,Australia,58684,United States of America,34707,Mozambique,28813,Canada,23729
267,0,1990056,South Africa,1990,Immigration,Mozambique,346433,Lesotho,187019,United Kingdom,117362,Zimbabwe,61875,Swaziland,34114
268,0,1995157,South Africa,1995,Emigration,United Kingdom,100971,Australia,61139,United States of America,49789,Canada,29983,Mozambique,29502
269,0,1995056,South Africa,1995,Immigration,Mozambique,320659,Lesotho,130897,United Kingdom,105771,Zimbabwe,82744,Swaziland,28635
270,0,2000157,South Africa,2000,Emigration,United Kingdom,136720,Australia,80640,United States of America,65171,Canada,36949,Mozambique,26952
271,0,2000056,South Africa,2000,Immigration,Mozambique,234274,Zimbabwe,127073,United Kingdom,124002,Lesotho,111888,Namibia,43615
272,0,2005157,South Africa,2005,Emigration,United Kingdom,159229,Australia,114160,United States of America,73064,New Zealand,39855,Canada,38430
273,0,2005056,South Africa,2005,Immigration,Zimbabwe,220867,Mozambique,220867,United Kingdom,148510,Lesotho,133937,Namibia,52210
274,0,2010157,South Africa,2010,Emigration,United Kingdom,194701,Australia,155930,United States of America,83406,New Zealand,48514,Canada,40555
275,0,2010056,South Africa,2010,Immigration,Zimbabwe,470423,Mozambique,294493,Lesotho,231928,United Kingdom,128581,Namibia,90408
276,0,2015157,South Africa,2015,Emigration,United Kingdom,200218,Australia,183370,United States of America,96214,New Zealand,56396,Canada,45353
277,0,2015056,South Africa,2015,Immigration,Zimbabwe,604248,Mozambique,370347,Lesotho,295504,Namibia,164558,United Kingdom,117019
278,0,2017157,South Africa,2017,Emigration,United Kingdom,210470,Australia,192251,United States of America,99405,New Zealand,57897,Canada,47152
279,0,2017056,South Africa,2017,Immigration,Zimbabwe,649385,Mozambique,381386,Lesotho,312537,Namibia,174043,United Kingdom,123764

In [3]:
migrantz = mf.master(male_migrants)

Cuba
El Salvador
Guatemala
Honduras
Mexico
Venezuela (Bolivarian Republic of)
China
India
Philippines
Viet Nam
Afghanistan
Iraq
Pakistan
Syrian Arab Republic
Ethiopia
Ghana
Kenya
Nigeria
Somalia
South Africa

In [4]:
migrantz.head()

,Code,Country,Year,Migration Type,Total Migration,Country 1,Country 1 Count,Country 2,Country 2 Count,Country 3,Country 3 Count,Country 4,Country 4 Count,Country 5,Country 5 Count
0,1990242,Cuba,1990,Emigration,835546,United States of America,736971,Spain,21854,Puerto Rico,19579,Venezuela (Bolivarian Republic of),11559,Dominican Republic,6824
0,1990195,Cuba,1990,Immigration,34555,Spain,10703,Russian Federation,4491,Haiti,2063,Ukraine,1367,United States of America,1186
0,1995242,Cuba,1995,Emigration,935377,United States of America,815617,Spain,28314,Puerto Rico,19293,Venezuela (Bolivarian Republic of),10603,Dominican Republic,7580
0,1995195,Cuba,1995,Immigration,26187,Spain,8112,Russian Federation,3404,Haiti,1564,Ukraine,1036,United States of America,899
0,2000242,Cuba,2000,Emigration,1049902,United States of America,894876,Spain,45738,Puerto Rico,19054,Italy,11659,Venezuela (Bolivarian Republic of),9928